#pragma once
#pragma once

#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>

#define LINHAS 5
#define COLUNAS 22

#define TAM_LINHAS_INTERFACE 9
#define TAM_COLUNAS_INTERFACE 22


#define TECLA_MENU_OPCAO_JOGAR 1
#define TECLA_MENU_OPCAO_TUTORIAL 2
#define TECLA_MENU_OPCAO_SAIR 3

#define TECLA_GAMEPLAY_DIRECIONAL_UP 88
#define TECLA_GAMEPLAY_DIRECIONAL_DOWN 22
#define TECLA_GAMEPLAY_DIRECIONAL_RIGHT 66
#define TECLA_GAMEPLAY_DIRECIONAL_LEFT 44
#define TECLA_GAMEPLAY_ACAO_CAPTURAR 55
#define TECLA_GAMEPLAY_ACAO_SOLTAR 33
#define TECLA_GAMEPLAY_ACAO_CANCELAR_JOGADA 11
#define TECLA_GAMEPLAY_ACAO_SAIR_DO_JOGO 118
#define TECLA_INVALIDA 999

#define AVISOS_SEM_AVISOS " "

#define VAZIO ' '

#define GAME_AVISO_COLISAO "VOCE PERDEU, SEU CARRO COLIDIU COM O CARRO INIMIGO!!!, APERTE F3"
#define GAME_CARRO_PLAYER '#'
#define GAME_CARRO_INIMIGO '$'
#define GAME_CARRO_COLISAO '@'
